# Workflow to build, test and deploy a Python function
name: Ejercicio Workflow

# On push to the A01352283 branch
on:
    push:
        branches: ["A01352283"]

# Jobs
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                python-version: "3.10"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f python3/requirements.txt ]; then pip install -r python3/requirements.txt; fi
                
            - name: Build
              run: |
                python python/src/app.py