name: CDCI Workflow

on:
  push:
    branches:
      [ '*' ]
  pull_request:
    branches:
      [ '*' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3