name: Ejercicio

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi

      - name: Do Lint testing
        run: |
          pylint app/main.py

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Test using pytest
        run: |
          pytest
