# This workflow

name: Lamba Example Exercise

on:
  push:
    branches: ["*" ]
  pull_request:
    branches: ["*"]

jobs:
    # This job will lint the code and make a build of the express application
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                    node-version: '18.x'
            - name: Install dependencies
              working-directory: ./lambda
              run: npm install
            #- run: npm ci Generally faster
            # - name: Lint code
            #   working-directory: ./app
            #   run: npm run lint:fix
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                    node-version: '18.x'
            - name: Test code
              working-directory: ./lambda
              run: npm run test
    # test:
    # # This job will run the unit tests
    # package:
    # # This job will package the application into a zip file
    # dockerize:
    # # This job will build the docker image
    # deploy:
    # # This job will deploy the docker image to AWS ECR
    # run:
    # # This job will run the docker image in a AWS lambda function