name: Tests for my name

on:
  push:
    branches:
      - A01751941
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f python3/requirements.txt ]; then pip install -r python3/requirements.txt; fi

    - name: Run tests with coverage to check for my name
      run: |
            RUN_ENV=dev 
            coverage run -m pytest python3/test/
            coverage report
            coverage html -d cc_report/
